version: "3"
services:
  localstack:
    image: localstack/localstack:4.14.0
    networks:
      - hmpps
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,sns

  tap-db:
    image: postgres
    networks:
      - hmpps
    container_name: tap-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=movements
      - POSTGRES_USER=external
      - POSTGRES_DB=movements

networks:
  hmpps:
