spring:
  jpa:
    show-sql: true
    properties:
      hibernate.generate_statistics: true
  datasource:
    hikari:
      connectionTimeout: 1000
      validationTimeout: 500
      maximumPoolSize: 5
      auto-commit: false
      data-source-properties:
        sslmode: 'disable'

db:
  server: "localhost:5432"
  name: "movements"
  user: "external"
  pass: "movements"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

hmpps.sqs:
  provider: localstack
  queues:
    hmppsdomaineventsqueue:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: hmppseventtopic
    offendereventsqueue:
      queueName: ${random.uuid}
      dlqName: ${random.uuid}
      subscribeTopicId: offendereventstopic
  topics:
    hmppseventtopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}
    offendereventstopic:
      arn: arn:aws:sns:eu-west-2:000000000000:${random.uuid}

service:
  domain-events:
    poll-interval: PT0s
  occurrence-status:
    poll-interval: PT0s
  ui-base-url: "https://local-ui"
  api-base-url: "http://local-api"
  version.key: version-key