package uk.gov.justice.digital.hmpps.externalmovementsapi.access

object Roles {
  const val EXTERNAL_MOVEMENTS_UI = "ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI"
  const val EXTERNAL_MOVEMENTS_RO = "ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS__RO"
  const val TEMPORARY_ABSENCE_RO = "ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO"
  const val TEMPORARY_ABSENCE_RW = "ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW"
  const val NOMIS_SYNC = "ROLE_EXTERNAL_MOVEMENTS__SYNC__RW"
}
