package uk.gov.justice.digital.hmpps.externalmovementsapi.access

import java.util.SequencedSet

object Roles {
  const val EXTERNAL_MOVEMENTS_UI = "ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS_UI"
  const val EXTERNAL_MOVEMENTS_RO = "ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS__RO"
  const val EXTERNAL_MOVEMENTS_RW = "ROLE_EXTERNAL_MOVEMENTS__EXTERNAL_MOVEMENTS__RW"
  const val TEMPORARY_ABSENCE_RO = "ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RO"
  const val TEMPORARY_ABSENCE_RW = "ROLE_EXTERNAL_MOVEMENTS__TEMPORARY_ABSENCE__RW"
  const val SCHEDULE_CLASHES_RO = "ROLE_SCHEDULES__CLASHES__RO"
  const val NOMIS_SYNC = "ROLE_EXTERNAL_MOVEMENTS__SYNC__RW"

  fun all(): SequencedSet<String> = linkedSetOf(
    EXTERNAL_MOVEMENTS_UI,
    EXTERNAL_MOVEMENTS_RO,
    EXTERNAL_MOVEMENTS_RW,
    TEMPORARY_ABSENCE_RO,
    TEMPORARY_ABSENCE_RW,
    SCHEDULE_CLASHES_RO,
    NOMIS_SYNC,
  )
}
