generic-service:
  nameOverride: hmpps-external-movements-api
  productId: "DPS125" # productId for the product that this belongs too, i.e. DPS001, see README.md for details

  replicaCount: 2
  resources:
    requests:
      cpu: 128m
      memory: 1024Mi
    limits:
      cpu: 2048m
      memory: 1280Mi

  image:
    repository: ghcr.io/ministryofjustice/hmpps-external-movements-api
    tag: app_version # override at deployment time
    port: 8080

  ingress:
    enabled: true
    host: app-hostname.local # override per environment
    tlsSecretName: hmpps-external-movements-api-cert
    annotations:
      nginx.ingress.kubernetes.io/server-snippet: |
        server_tokens off;
        location /queue-admin/retry-all-dlqs {
          deny all;
          return 401;
        }

  # Used to access resources like S3 buckets, SQS queues and SNS topics
  serviceAccountName: hmpps-external-movements-api

  # Environment variables to load into the deployment
  env:
    JDK_JAVA_OPTIONS: "-Xmx512m -XX:+UseG1GC"
    SERVER_PORT: "8080"
    DB_SSL_MODE: "verify-full"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  namespace_secrets:
    hmpps-external-movements-api-application-insights:
      APPLICATIONINSIGHTS_CONNECTION_STRING: "APPLICATIONINSIGHTS_CONNECTION_STRING"
    hmpps-external-movements-api:
      CLIENT_ID: "SYSTEM_CLIENT_ID"
      CLIENT_SECRET: "SYSTEM_CLIENT_SECRET"
    rds-postgresql-instance-output:
      DB_SERVER: "rds_instance_address"
      DB_NAME: "database_name"
      DB_USER: "database_username"
      DB_PASS: "database_password"
    hmpps-domain-events-topic:
      HMPPS_SQS_TOPICS_HMPPSEVENTTOPIC_ARN: "topic_arn"
    domain-events-queue-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_QUEUE_NAME: "queue_name"
    domain-events-dlq-secret:
      HMPPS_SQS_QUEUES_HMPPSDOMAINEVENTSQUEUE_DLQ_NAME: "queue_name"

  allowlist:
    groups:
      - digital_staff_and_mojo
      - moj_cloud_platform

  retryDlqCronjob:
    enabled: true
    retryDlqSchedule: "0/30 * * * *"

generic-prometheus-alerts:
  targetApplication: hmpps-external-movements-api
